# Generated by Django 5.1.4 on 2025-01-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0007_remove_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='new_sender',
            new_name='sender',
        ),
    ]
